[package]
name = "subway"
version = "0.1.0"
edition = "2024"

[dependencies]
salvo = { version = "0.83.0", features = ["acme", "quinn", "oapi"] }
tokio = "1.47.1"
serde = { version = "1.0.219", features = ["derive"] }
uuid = { version = "1.17.0", features = ["v4"] }