services:
  db:
    image: postgres:17.6
    container_name: postgres-db
    restart: unless-stopped
    ports:
      - "5432:5432" # TODO not prod-ready
    environment:
      POSTGRES_USER: benchmarkdbuser # TODO not prod-ready
      POSTGRES_PASSWORD: benchmarkdbpass # TODO not prod-ready
      POSTGRES_DB: mydatabase # TODO not prod-ready
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U benchmarkdbuser -d mydatabase" ] # TODO not prod-ready
      interval: 5s
      timeout: 5s
      retries: 5

  # TODO not prod-ready
  keycloak:
    image: keycloak/keycloak:26.3.4-0
    container_name: keycloak
    restart: unless-stopped
    ports:
      - "8989:8989" # TODO not prod-ready
    environment:
      KEYCLOAK_ADMIN: my_example_admin_user
      KEYCLOAK_ADMIN_PASSWORD: my_example_password
    command: start-dev

  subway-backend:
    image: subway-backend
    container_name: subway-backend
    restart: unless-stopped
    ports:
      - "7878:7878" # TODO not prod-ready
    environment:
      DATABASE_URL: postgres://benchmarkdbuser:benchmarkdbpass@db:5432/mydatabase # TODO not prod-ready
    depends_on:
      db:
        condition: service_healthy

  subway-frontend:
    image: subway-frontend
    container_name: subway-frontend
    restart: unless-stopped
    ports:
      - "4173:4173" # TODO not prod-ready

volumes:
  pgdata: