services:
  db_container:
    image: postgres:17.6
    container_name: postgres-db
    restart: unless-stopped
    ports:
      - "2345:5432" # TODO not prod-ready
    environment:
      POSTGRES_USER: postgres_user # TODO not prod-ready
      POSTGRES_PASSWORD: postgres_password # TODO not prod-ready
      POSTGRES_DB: postgres_db # TODO not prod-ready
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgres_db" ] # TODO not prod-ready
      interval: 1s
      retries: 120

  # TODO not prod-ready
  subway-keycloak:
    image: subway-keycloak
    container_name: subway-keycloak
    restart: unless-stopped
    ports:
      - "8989:8080" # TODO not prod-ready
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: kc_bootstrap_admin_username # use this to log in at localhost:8989
      KC_BOOTSTRAP_ADMIN_PASSWORD: kc_bootstrap_admin_password # use this to log in at localhost:8989
    command: --import-realm # TODO development node, not prod-ready
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    healthcheck:
      #
      # exec 3<>/dev/tcp/localhost/9000        -- open a TCP connection using bash's built-in support for TCP sockets
      # echo -e "GET /health ...               -- send a GET request to the /health/ready endpoint. The result will look like
      #
      #   HTTP/1.1 200 OK
      #   content-type: application/json; charset=UTF-8
      #   cache-control: no-store
      #   connection: close
      #   content-length: 145
      #
      #   {
      #       "status": "UP",
      #       "checks": [
      #           {
      #               "name": "Keycloak cluster health check",
      #               "status": "UP"
      #           }
      #       ]
      #   }
      #
      # cat <&3 | grep -q "\"status\": \"UP\"" -- succeeds if the output of file descriptor 3 contains the string '\"status\": \"UP\"'
      # || exit 1                              -- if grep does not find "200 OK", fail the health check
      #
      test: [ "CMD", "/bin/bash", "-c", 'exec 3<>/dev/tcp/localhost/9000 && echo -e "GET /health/ready HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep -q "\"status\": \"UP\"" || exit 1' ]
      interval: 1s
      retries: 120

  subway-backend:
    image: subway-backend
    container_name: subway-backend
    restart: unless-stopped
    ports:
      - "7878:7878" # TODO not prod-ready. Also, keep these the same so running in / outside a container uses the same port
    environment:
      SUBWAY_DB_URL: postgresql://postgres_user:postgres_password@db_container:5432/postgres_db # TODO not prod-ready
      SUBWAY_DB_MODE: docker
    depends_on:
      db_container:
        condition: service_healthy
      subway-keycloak:
        condition: service_healthy
    healthcheck:
      #
      # exec 3<>/dev/tcp/localhost/7878 -- open a TCP connection using bash's built-in support for TCP sockets
      # echo -e "GET /health ...        -- send a GET request to the /health endpoint. The result will look like
      #
      #   HTTP/1.1 200 OK
      #   access-control-allow-credentials: true
      #   vary: origin
      #   vary: access-control-request-method
      #   vary: access-control-request-headers
      #   connection: close
      #   content-length: 0
      #
      # cat <&3 | grep -q "200 OK"      -- succeeds if the output of file descriptor 3 contains the string '200 OK'
      # || exit 1                       -- if grep does not find "200 OK", fail the health check
      #
      test: [ "CMD", "/bin/bash", "-c", 'exec 3<>/dev/tcp/localhost/7878 && echo -e "GET /health HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep -q "200 OK" || exit 1' ]
      interval: 1s
      retries: 120

  subway-frontend:
    image: subway-frontend
    container_name: subway-frontend
    restart: unless-stopped
    ports:
      - "5173:5173" # TODO not prod-ready. Also, keep these the same so running in / outside a container uses the same port
    environment:
      VITE_SUBWAY_AUTH_MODE: keycloak
    depends_on:
      subway-backend:
        condition: service_healthy
    command: ["serve", "-s", "dist", "-l", "5173"] # overrides the CMD in the container so the port can be customized

volumes:
  pgdata: