services:
  db:
    image: postgres:17.6
    container_name: postgres-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: benchmarkdbuser
      POSTGRES_PASSWORD: benchmarkdbpass
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U benchmarkdbuser -d mydatabase" ]
      interval: 5s
      timeout: 5s
      retries: 5

  subway-backend:
    image: subway-backend
    container_name: subway-backend
    restart: unless-stopped
    ports:
      - "7878:7878"
    environment:
      DATABASE_URL: postgres://benchmarkdbuser:benchmarkdbpass@db:5432/mydatabase
    depends_on:
      db:
        condition: service_healthy

  subway-frontend:
    image: subway-frontend
    container_name: subway-frontend
    restart: unless-stopped
    ports:
      - "4173:4173"

volumes:
  pgdata: